### PR TITLE
feat: Make `IOPTranscript` publicly accessible

### PR DESCRIPTION
**Pull request by tessico**
## Description

The jellyfish `IOPTranscript` has very ergonomic wrappers around merlin, why not expose it publicly.
Also I added an extra convenience method for getting challenge bytes instead of field elements.
Not sure whether this is a good approach - instead one could make the `transcript` field of the struct public and allow users to call more methods directly from merlin.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (main)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Review by chancharles92 — COMMENTED** [review]
Thanks @tessico , LGTM, could you also fix the lint failure?

**Review by chancharles92 — APPROVED** [review]

**Comment by tessico** [comment]
Hmm I'm new to this action, but I can't find why CI is failing - the title seems to conform the guidelines, unless I'm missing sth?

**Comment by chancharles92** [comment]
> Hmm I'm new to this action, but I can't find why CI is failing - the title seems to conform the guidelines, unless I'm missing sth?

@mrain @alxiong Do you know what's the reason for PR title failing?

**Comment by mrain** [comment]
> > Hmm I'm new to this action, but I can't find why CI is failing - the title seems to conform the guidelines, unless I'm missing sth?
> 
> @mrain @alxiong Do you know what's the reason for PR title failing?

The reason maybe the permission setting of this PR: https://github.com/EspressoSystems/jellyfish/blob/1b03cada0ac48607fd8490a6115abc3070811757/.github/workflows/commit-title.yaml#L10C5-L10C5

Since it only checks the title, could we remove the "write" requirement here? cc @alxiong  @Ancient123

**Comment by alxiong** [comment]
the best action is go to "Setting" of this repo and grant write permission to this Action. which will be done by @Ancient123

**Comment by Ancient123** [comment]
Try rebasing? If that doesn't work, I can do an administrator merge.

**Comment by alxiong** [comment]
if we can't figure out why the commitlint CI fails, let's just merge it first, there's no problem with the commit message of this PR @mrain

**Comment by mrain** [comment]
> the best action is go to "Setting" of this repo and grant write permission to this Action. which will be done by @Ancient123 (as I have communicated with him on Zulip)

I don't have access the settings of this repo. Could you try this and see if it proceeds? cc @alxiong @Ancient123 
If no let's go ahead and merge it ignoring CI failure.

**Pull request merged**
