### PR TITLE
refactor: use BigEndian for SolidityTranscript

### PR DESCRIPTION
**Pull request by alxiong**
closes: #618 

### This PR: 

Changes behavior of `SolidityTranscript`, see the linked issue for description

### This PR does not:

Question: should we also optionally append `tau` for circuits that does support lookup? currently in contract, we have to do [a useless `get_and_append_challenge` call ](https://github.com/EspressoSystems/espresso-sequencer/blob/main/contracts/src/libraries/PlonkVerifier.sol#L192-L194)for this unused challenge.

@chancharles92 @philippecamacho 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (main)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added relevant changelog entries to the `CHANGELOG.md` of touched crates.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by alxiong** [comment]
Somehow there's still one test failed after [ce7cff8](https://github.com/EspressoSystems/jellyfish/pull/619/commits/ce7cff8e8e861ec11b18bc5ab23707b7dcfdc0d2). 

after some digging, I'm unable to locate the cause. @chancharles92 you are probably more familiar with this gadget, do you have any clue where did i forget to update?

**Comment by alxiong** [comment]
reminder for myself after I address comments for this PR: 

- [ ] update changelog, and bump version as I forgot to do in a previous PR

**Review by mrain — APPROVED** [review]
Generally LGTM. 

I agree with the removal of state field inside SolidityTranscript struct, because anyway it's not used to construct the hasher. Same field also exists in the RescueTranscript, we should consider removing that as well.

**Comment by philippecamacho** [comment]
Should not we add an `if` statement to raise an error [here](https://github.com/EspressoSystems/jellyfish/blob/88c65c499c38aaf511cb24310c421daaad8dc55a/plonk/src/transcript/mod.rs#L171) if the plonk instance does not support lookups?

**Review by philippecamacho — APPROVED** [review]
Added a minor comment. LGTM.

**Comment by alxiong** [comment]
> because anyway it's not used to construct the hasher.

yes, but previously, we were using it. in this PR, we removed it.

> Same field also exists in the RescueTranscript, we should consider removing that as well.

that would require refactoring of the recursion circuit, since we are not using it atm, maybe we leave it as it is for now.

cc @mrain

**Comment by alxiong** [comment]
> Should not we add an if statement to raise an error [here](https://github.com/EspressoSystems/jellyfish/blob/88c65c499c38aaf511cb24310c421daaad8dc55a/plonk/src/transcript/mod.rs#L171) if the plonk instance does not support lookups?

we have already does the protection from the caller side: in `snark.rs`
```rust
            let plookup_evals = if circuits[i].support_lookup() {
                let evals = prover.compute_plookup_evaluations(
                    prove_keys[i],
                    &challenges,
                    &online_oracles[i],
                )?;
                transcript.append_plookup_evaluations::<E>(&evals)?;
                Some(evals)
            } else {
                None
            };
```

we only invoke it if `.supports_lookup()` evaluates to true.

**Comment by alxiong** [comment]
maintainer check: @mrain are you happy with `jf-plonk`-only bump in [4c421e7](https://github.com/EspressoSystems/jellyfish/pull/619/commits/4c421e7968c934733567a6a5b03a66839f3fa5e2)?

**Review by philippecamacho — APPROVED** [review]
LGTM

**Review by mrain — APPROVED** [review]

**Pull request merged**
