### PR TITLE
Bug fixed. `logic_or` should use `LogicOrValueGate`

### PR DESCRIPTION
**Pull request by mrain**
## Description

closes: #114 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (main)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] ~Updated relevant documentation in the code~
- [x] ~Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`~
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by alxiong** [comment]
I don't understand, why is there a `LogicOrValueGate` in the first place? that seems equivalent to `LogicOrGate`?

**Comment by chancharles92** [comment]
I remember we used to have APIs `c = logic_or(a, b)` and `logic_or_gate(c, a, b)`: the first return a bool variable `c` that's the logic_or of the inputs; the 2nd API enforces `c = a or b`. So what's the `LogicOrValueGate`?

**Comment by mrain** [comment]
> I don't understand, why is there a `LogicOrValueGate` in the first place? that seems equivalent to `LogicOrGate`?
> basically `LogicOrGate`: `a+b-ab-1 =0` and `LogicOrValueGate`: `a+b-ab=1`, they are the same.

Not really the same. For `LogicOrValueGate` is `a+b-ab=output`, that's `q_o` not `q_c`

> I remember we used to have APIs c = logic_or(a, b) and logic_or_gate(c, a, b): the first return a bool variable c that's the logic_or of the inputs; the 2nd API enforces c = a or b. So what's the LogicOrValueGate?

We only have APIs `c = logic_or(a, b)` and `logic_or_gate(a, b)`. Later one is a hard constraint that `a` or `b` must be true.
`LogicOrGate` corresponds to the later constraint. And `LogicOrValueGate` is computing the logic or of two input wires.

**Comment by chancharles92** [comment]
@mrain Is there a better name for `LogicOrValueGate`? How about `LogicOrOutputGate`?

**Comment by mrain** [comment]
> @mrain Is there a better name for `LogicOrValueGate` and `LogicOrGate`? How about `LogicOrOutputGate` and `LogicOrConstantGate`?

What about `LogicOrGate` and `LogicOrOutputGate`? That's clear enough to me.
WDYT @alxiong

**Review by chancharles92 — APPROVED** [review]
LGTM

**Pull request merged**
