### PR TITLE
Release 0.1.1

### PR DESCRIPTION
**Pull request by bfish713**
## Description

Preparing a release for Seahorse to pin to.  This just updates the cargo.toml to match what I plan to tag as the release.
---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (main)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests - N/A
- [ ] Updated relevant documentation in the code - N/A
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md` - N/A
- [x] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by alxiong** [comment]
any pending items in CHANGELOG that the downstream wants to use @bfish713 ? (probably the derived`Snafu,Debug` traits on some structs?)

**Comment by bfish713** [comment]
> any pending items in CHANGELOG that the downstream wants to use @bfish713 ? (probably the derived`Snafu,Debug` traits on some structs?)

Nothing in particular, we just need some version to pin Seahorse to

**Review by alxiong — APPROVED** [review]

**Comment by alxiong** [comment]
a minor mishap for this PR, now I realize, is that we forgot to update our CHNAGELOG.

Should we move everything in our "Pending" sections to a new "v0.x.x Change Summary" section?
(cc @zhenfeizhang )

**Comment by zhenfeizhang** [comment]
lol may be we can update for major versions and ignore minors ;-)

**Pull request merged**
