### PR TITLE
fix cargo udeps failure in ci

### PR DESCRIPTION
**Pull request by alxiong**
## Description

Fixing periodic check on unused dep in CI: https://github.com/EspressoSystems/jellyfish/actions/runs/4969545780

### CODE REVIEW

**Review by mrain — COMMENTED** [review]
Is it better to add a required feature in the example?
Like [here](https://github.com/EspressoSystems/jellyfish/pull/256/files#diff-4336bdd5f194d1847c08e50879d78c7fb123197d41577baa9206771cc1b4ed0bR56).

**Review by Ancient123 — APPROVED** [review]

**Comment by Ancient123** [comment]
Seems fine to me. But @mrain has a good idea as well.

**Comment by alxiong** [comment]
> Is it better to add a required feature in the example?

done in [944b771](https://github.com/EspressoSystems/jellyfish/pull/257/commits/944b77112b6a61767f6f4086ffe2e0f6e928f97d)
(thanks for the suggestion, I didn't know this feature before)

**Review by mrain — APPROVED** [review]
LGTM

**Pull request merged**
