### PR TITLE
Clean up deps

### PR DESCRIPTION
**Pull request by tessico**
## Description

Related to https://github.com/EspressoSystems/jellyfish/issues/127, but not closing it yet.
This is just an easy win since `cargo-udeps` might still leave some unused deps undetected. At some point I'll review them one-by-one.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (main)
- [ ] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Comment by alxiong** [comment]
is there a way to add this check in our CI? (even if there's false positive, it will be better than nothing)

**Comment by tessico** [comment]
With a small hackaround I've added the [cargo-udeps-action](https://github.com/aig787/cargo-udeps-action).
The caveat there is that `cargo-udeps` requires `nightly` toolchain, but placing this action in an expected place (e.g. after the audit step) would default to `stable`, thus [failing](https://github.com/tessico/jellyfish/actions/runs/3620978377/jobs/6103852259) the job. 

I've opened an issue in the action's repo: https://github.com/aig787/cargo-udeps-action/issues/1, currently using the workaround described there.

**Comment by alxiong** [comment]
I see, is it correct to conclude that just running `cargo +nightly udeps` in CI will require 2~3 min alone? (downloading nightly toolchain can be cached and not counted here), that's way slower than I expect. 

Thanks for the effort of different experimentations.

A possible alternative is to add this to our pre-commit hook instead. which I think is probably better, wdyt?

**Comment by tessico** [comment]
@alxiong Well no, just running udeps by itself will be faster than that. My point was that most of the 2-3 minutes is spent on the download.

**Comment by tessico** [comment]
Locally it takes ~18s, I expect it to stay under 30s on the GitHub ubuntu machine, discounting the download.
I honestly would prefer to not spend another 18s on waiting for a local commit.

**Comment by tessico** [comment]
Maybe we can make it a separate cron job, say once a week on the jellyfish repo.

**Comment by tessico** [comment]
I've moved the check to its own workflow. It is triggered weekly as a cron, or otherwise can be triggered manually, e.g. see [this run](https://github.com/tessico/jellyfish/actions/runs/3640096070/jobs/6144318827).

Currently jobs are failing due to an update in espresso-common re tags, see https://github.com/EspressoSystems/jellyfish/issues/155.

**Review by alxiong — APPROVED** [review]

**Pull request merged**
