### PR TITLE
Performance optimizations

### PR DESCRIPTION
**Pull request by tudorpintea999**
Hello
I made some small changes to optimize a bit of your code.
It s not much but it s honest work and hope it helps Espresso sys 
Best regards
Tudor

### CODE REVIEW

**Comment by alxiong** [comment]
For god sake, the typo fixing bot has upgraded into renaming and code shuffling bot. 

Thank you AI.

**Comment by mrain** [comment]
> For god sake, the typo fixing bot has upgraded into renaming and code shuffling bot.

I wonder if these's an LLM backed `typos`

**Comment by tudorpintea999** [comment]
@alxiong @mrain i tried to help using chat gpt, not expecting any airdrop or so..

**Comment by alxiong** [comment]
> @alxiong @mrain i tried to help using chat gpt, not expecting any airdrop or so..

fair enough, thanks for your effort! 
IMHO, the LLM suggestions are bad (esp. with a vaguely defined goal, say "improve this code, its documentation and remove unnecessary logic")

removing necessary (and defense in depth) unit tests is not helping. (which is what this PR does, for example, it removes all the trait implementation for `aead::EncKey` and all the serde-related tests, why? 🤷‍♂️ ) 

I do agree that our code doc is far from perfect and their clarity can always improve. (same applies to actual code)

but it's impossible to carefully review a PR with such large diff. It's also extremely hard to judge the actual quality improvement. 

If you have concrete concern or improvement idea to our code and code comment, we always warmly welcome you creating an issue and we can discuss in the issue threads about the problems and potential solutions. Then you can chartered towards submitting a PR implementing the agreed upon solution. This will save both yours and maintainers' time.

**Pull request closed without merging**
