### PR TITLE
Fixing some trait bound

### PR DESCRIPTION
**Pull request by alxiong**
## Description

Major changes include:
- A missing modification for #87 in 6ee2ac08bdf910bf05bcd141a6e903b8b3e57131
- Remove unnecessary `Clone` on some trait bound: `P: Parameters + Clone` -> `P: Parameters`, whose source is our `trait Gate`, and trick I use is by relying on object-safe [`dyn_clone`](https://github.com/dtolnay/dyn-clone)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (main)
- [x] ~Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.~
- [x] ~Wrote unit tests~
- [x] ~Updated relevant documentation in the code~
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md` (@zhenfeizhang I don't think we need to add this to changelog, WDYT?)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Review by zhenfeizhang — APPROVED** [review]
In general LGTM. A question: why do we need `CloneGate` in the first place? Is it possible to simply remove `impl<F: Field> Clone for Box<dyn Gate<F>>`?

**Review by mrain — APPROVED** [review]
LGTM.

**Comment by alxiong** [comment]
> why do we need CloneGate in the first place? Is it possible to simply remove impl<F: Field> Clone for Box<dyn Gate<F>>?

because of [this](https://stackoverflow.com/questions/30353462/how-to-clone-a-struct-storing-a-boxed-trait-object/). I was using the suggested answer there, until I saw the better option below (i.e `dyn_clone` crate)

**Comment by zhenfeizhang** [comment]
> > why do we need CloneGate in the first place? Is it possible to simply remove impl<F: Field> Clone for Box<dyn Gate>?
> 
> because of [this](https://stackoverflow.com/questions/30353462/how-to-clone-a-struct-storing-a-boxed-trait-object/). I was using the suggested answer there, until I saw the better option below (i.e `dyn_clone` crate)

Thanks!

**Pull request merged**
