### PR TITLE
Implement gadgets for append-only MT with rate-3 Rescue

### PR DESCRIPTION
**Pull request by tessico**
## Description

Replacement for https://github.com/EspressoSystems/jellyfish/pull/138 after mt-refactor has been merged.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (main)
- [x] Linked to GitHub issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the GitHub PR explorer

### CODE REVIEW

**Review by mrain — APPROVED** [review]
LGTM.

**Review by chancharles92 — APPROVED** [review]
Also LGTM 👍

**Review by alxiong — COMMENTED** [review]
Sorry for my late review, but I feel that this PR didn't address the ergonomic issue I raised up in the first place in #88.

other problems include: while our MT impl has become very generic, our gadget is only supports `RescueMerkleTree::<F>` <-- this is not reflective just from our gadget API.

Concretely, the gadget API can be more intuitive imo. See my comments here: https://github.com/EspressoSystems/jellyfish/issues/88#issuecomment-1327381539

**Comment by tessico** [comment]
@alxiong You're right in that it's a gadget very specific for one concrete instantiation of the MT. As discussed [here](https://github.com/EspressoSystems/jellyfish/pull/138#discussion_r1026763507), we are still planning to make it more generic.

I think you have a good point in re-opening the issue. This PR was intended more as a refresh of our old MT gadget (which was also for a concrete instantiation of an MT) to match with the new API introduced in `mt-refactor` branch, rather than re-designing the APIs.

Some related tasks:
1. WIP PR for refactoring the sponge APIs: https://github.com/EspressoSystems/jellyfish/pull/146
2. issue for making `MerkleTreeGadget` more generic: https://github.com/EspressoSystems/jellyfish/issues/142
3. now the re-opened https://github.com/EspressoSystems/jellyfish/issues/88

I guess the above order is only natural given how they depend on one another, with potentially some though on doing 2nd and 3rd in parallel to avoid too much redesign.

**Comment by alxiong** [comment]
I see, makes sense! thanks for the clarification.

**Pull request merged**
